const input = require('fs')
    .readFileSync(`${__dirname}/day15-input.txt`)
    .toString()
console.time('part 1')
console.log(`day 15 part 1 - result is: ${require('./15-1.js')(input)}`)
console.timeEnd('part 1')
console.time('part 2')
console.log(`day 15 part 2 - result is: ${require('./15-2.js')(input)}`)
console.timeEnd('part 2')
